>>>>><h1><font color="teal">Neural network</font></h1>

In [2]:
import numpy as np

X =np.array([[0.04416006, 0.95665297],
       [0.43614665, 0.94897731],
       [0.78630599, 0.866289378],
       [0.17316542, 0.07494859],
       [0.60074272, 0.16797218],
       [0.73338017, 0.40844386],
       [0.52790882, 0.93757158],
       [0.52169612, 0.10819338],
       [0.15822341, 0.54520265],
       [0.52440408, 0.63761024],
       [0.40149544, 0.64980511]])
y = np.array([[0],[0],[1],[1],[1],[0],[1],[0],[0],[1],[0]])


In [3]:
print(type(X),type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
X

array([[0.04416006, 0.95665297],
       [0.43614665, 0.94897731],
       [0.78630599, 0.86628938],
       [0.17316542, 0.07494859],
       [0.60074272, 0.16797218],
       [0.73338017, 0.40844386],
       [0.52790882, 0.93757158],
       [0.52169612, 0.10819338],
       [0.15822341, 0.54520265],
       [0.52440408, 0.63761024],
       [0.40149544, 0.64980511]])

In [5]:
y

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [6]:
class NN:
    def __init__(self, input_dim, hidden_dim, output_dim):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.W1 = np.random.randn(self.input_dim, self.hidden_dim)
        self.b1 = np.zeros((1, self.hidden_dim))
        self.W2 = np.random.randn(self.hidden_dim, self.output_dim)
        self.b2 = np.zeros((1, self.output_dim))
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def softmax(self, x):
        exp_x = np.exp(x)
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)
 
        
    def forward(self, X):
        # Forward propagation
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.sigmoid(self.z1)
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        
        if self.output_dim == 1:
            self.output = self.sigmoid(self.z2)
        else:
            self.output = self.softmax(self.z2)
            
        return self.output
    
    
    
    def backward(self, X, y, output, learning_rate):
        # Backward propagation
        if self.output_dim == 1:
            error = y - output
            delta_output = error * self.sigmoid_derivative(output)
        else:
            error = y - output
            delta_output = error
            
        delta_hidden = np.dot(delta_output, self.W2.T) * self.sigmoid_derivative(self.a1)
        
        # Update weights and biases
        self.W2 += learning_rate * np.dot(self.a1.T, delta_output)
        self.b2 += learning_rate * np.sum(delta_output, axis=0, keepdims=True)
        self.W1 += learning_rate * np.dot(X.T, delta_hidden)
        self.b1 += learning_rate * np.sum(delta_hidden, axis=0)
        
    def train(self, X, y, epochs, learning_rate):
        for i in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output, learning_rate)
            
    def predict(self, X):
        output = self.forward(X)
        if self.output_dim == 1:
            predictions = (output > 0.5).astype(int)
        else:
            predictions = np.argmax(output, axis=1)
        return predictions


### Initialize neural network model

In [7]:
input_dim = 2
hidden_dim = 4
output_dim = 1
nn =NN(input_dim, hidden_dim, output_dim)

### Train the model

In [8]:
epochs = 1000
learning_rate = 0.1
nn.train(X, y, epochs, learning_rate)

## Compute the loss

In [19]:
output = nn.forward(X)
loss = np.mean((y - output) ** 2)
print("Loss:", loss)


Loss: 0.24342893721251938


## Generate new data for prediction

In [20]:

X_new = np.random.rand(5, 2)

# Make predictions on new data
y_new = nn.predict(X_new)

print("New data:\n", X_new)
print("Predictions:\n", y_new)


New data:
 [[0.22971061 0.93143391]
 [0.28744801 0.9746435 ]
 [0.42676941 0.6460856 ]
 [0.87957589 0.52152525]
 [0.18480616 0.25844951]]
Predictions:
 [[0]
 [0]
 [0]
 [0]
 [0]]


### Calculate accuracy 

In [ ]:
X_test = np.random.rand(100, 2)
y_test = np.random.randint(0, 2, size=(100, 1))

In [21]:
# Make predictions on test dataset
predictions = nn.predict(X_test)

# Calculate accuracy
accuracy = np.mean(predictions == y_test)
print("Accuracy:", accuracy)


Accuracy: 0.61


In [22]:
X_test.size

200

In [ ]:
import numpy as np

In [9]:

class InputLayer:
    def __init__(self, input_dim, hidden_layer):
        self.input_dim = input_dim
        self.hidden_layer = hidden_layer
        
    def forward(self, X):
        self.output = X
        return self.hidden_layer.forward(X)

class HiddenLayer:
    def __init__(self, input_dim, hidden_dim, output_layer, activation_function):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_layer = output_layer
        self.activation_function = activation_function
        
        self.W = np.random.randn(self.input_dim, self.hidden_dim)
        self.b = np.zeros((1, self.hidden_dim))
        
    def forward(self, X):
        self.z = np.dot(X, self.W) + self.b
        self.output = self.activation_function(self.z)
        return self.output_layer.forward(self.output)
    
    def backward(self, delta_output, learning_rate):
        delta_hidden = np.dot(delta_output, self.output_layer.W.T) * self.activation_function_derivative(self.output)
        self.W += learning_rate * np.dot(self.input_layer.output.T, delta_hidden)
        self.b += learning_rate * np.sum(delta_hidden, axis=0)
 
    def activation_function_derivative(self, x):
        if self.activation_function == 'sigmoid':
            return x * (1 - x)
        elif self.activation_function == 'relu':
            return np.where(x > 0, 1, 0)
        elif self.activation_function == 'tanh':
            return 1 - x ** 2
        
class OutputLayer:
    def __init__(self, input_layer, hidden_layer, output_dim, activation_function):
        self.input_layer = input_layer
        self.hidden_layer = hidden_layer
        self.output_dim = output_dim
        self.activation_function = activation_function
        
        self.W = np.random.randn(self.hidden_layer.hidden_dim, self.output_dim)
        self.b = np.zeros((1, self.output_dim))
        
    def forward(self, X):
        self.z = np.dot(X, self.W) + self.b
        if self.activation_function == 'sigmoid':
            self.output = self.sigmoid(self.z)
        elif self.activation_function == 'softmax':
            self.output = self.softmax(self.z)
        return self.output
    
    def backward(self, y, learning_rate):
        self.hidden_layer.backward(delta_output, learning_rate)
        self.W += learning_rate * np.dot(self.hidden_layer.output.T, delta_output)
        self.b += learning_rate * np.sum(delta_output, axis=0, keepdims=True)
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def softmax(self, x):
        exp_x = np.exp(x)
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)
    

class NN:
    def __init__(input_layer,hidden_layer,output_dim,learning_rate,activation_function):
        self.input=input_layer
        self.hidden=hidden_layer
        self.output=output_dim
        self.activation=activattion_function
        
        self.W = np.random.randn(self.hidden_layer.hidden_dim, self.output_dim)
        self.b = np.zeros((1, self.output_dim))
        
    def forward (self,X):
        self.z=np.dot(X,self.W)+self.b
        if self.activation_function =='sigmoid':
            self.output=self.
        
